---
title: "Lab 2"
author: 
  - Makayla Whitney
  - Joe Swinehart
  - Janette Avelar
  - David Fainstein
date: "1/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r raw data}
if(!require(fivethirtyeight)) install.packages("fivethirtyeight", repos = "http://cran.us.r-project.org")
remotes::install_github("fivethirtyeightdata/fivethirtyeightdata")
library(fivethirtyeight)
library(fivethirtyeightdata)
library(here)
library(tidyverse)
library(lubridate)
```

Visualize the change in trends for each hurricane over time in one plot with three scales. Map color to a discrete scale.
```{r google trends viz 1}

trends_clean <- google_trends %>% 
  pivot_longer(c(`hurricane_harvey_us`, `hurricane_irma_us`, `hurricane_maria_us`, `hurricane_jose_us`), names_to = "Hurricane", values_to = "Ranking")


ggplot(data=trends_clean, aes(x=date, y=Ranking, color = Hurricane))+
geom_line()+ 
  labs(title = "Google Search Popularity", 
       subtitle = "According to the Google Trends dashboard",
       x = "Date",
       y = "Search Ranking")
  

```

Visualize the trends again, this time with solid shapes.
```{r google trends viz 2}
#Geom_ribbons have updated ymin & ymax so they appear on the figures
#thanks, David...I couldn't figure it out!
trends_clean %>% 
  ggplot(aes(date, Ranking)) + 
  geom_line()+
  geom_ribbon(aes(
    ymin = 0, 
    ymax = Ranking), 
    fill = "cornflowerblue",
    alpha = .85)+
  facet_wrap(~Hurricane, ncol = 1) +
  theme_minimal()+
  labs(title = "Google Search Popularity", 
       subtitle = "According to the Google Trends dashboard",
       x = "Date",
       y = "Search Ranking")
  

```

Same relationship, but mapped to a continuous scale.

```{r google trends viz 3}

  ggplot(trends_clean, aes(date, Hurricane)) + 
  geom_tile(aes(fill=Ranking)) +
  scale_fill_viridis_c(option = "plasma") +
  theme_minimal()+
  labs(title = "Google Search Popularity", 
       subtitle = "According to the Google Trends dashboard",
       x = "Date",
       y = "Hurricane")

```

```{r google trends viz 4}


```

```{r tv states viz}
#Near replication of the 538 figure
ggplot(tv_states) +
#Placing lines first
  geom_line(aes(x = date, y = florida), color = "#FFFFFF") +   
  geom_line(aes(x = date, y = texas), color = "#FFFFFF") + 
  geom_line(aes(x = date, y = puerto_rico), color = "#FFFFFF") +  
#Filling in ribbons second  
  geom_ribbon(aes(x = date, y = florida, ymin = 0, ymax = florida), fill = "deeppink2", alpha = 0.98) +   
  geom_ribbon(aes(x = date, y = texas, ymin = 0, ymax = texas), fill = "sienna2", alpha = 0.98) + 
  geom_ribbon(aes(x = date, y = puerto_rico, ymin = 0, ymax = puerto_rico), fill = "cyan2", alpha = 0.98) +  
#Identifying incidents (e.g., hurricane landfalls)
  geom_text(aes(x = as.Date("2017-08-25"), y = 3.1, label = "Harvey\nLandfall"), size = 4, color = "grey") +
  geom_vline(xintercept = as.Date("2017-08-25"), linetype = "dotted", color= "grey", size = 0.75) +
  geom_text(aes(x = as.Date("2017-09-07"), y = 3.3, label = "Irma\nLandfall"), size = 4, color = "grey") +
  geom_vline(xintercept = as.Date("2017-09-07"), linetype = "dotted", color= "grey", size = 0.75) +
  geom_text(aes(x = as.Date("2017-09-18"), y = 2.1, label = "Maria\nLandfall"), size = 4, color = "grey") +
  geom_vline(xintercept = as.Date("2017-09-18"), linetype = "dotted", color= "grey", size = 0.75) +
  geom_text(aes(x = as.Date("2017-10-01"), y = 2.7, label = "Las Vegas\nshooting"), size = 4, color = "grey") +
  geom_vline(xintercept = as.Date("2017-10-01"), linetype = "dotted", color= "grey", size = 0.75) +
#Labeling each state  
  geom_text(aes(x = as.Date("2017-08-28"), y = 0.8, label = "Texas"), size = 5, color = "black") +
  geom_text(aes(x = as.Date("2017-09-09"), y = 1.5, label = "Florida"), size = 5, color = "black") +
  geom_text(aes(x = as.Date("2017-10-01"), y = 1.35, label = "Puerto Rico"), size = 5, color = "black") +  
  labs(x = "",
       y = "Share of sentences",
       title = "National Cable News Networks") +
  theme_minimal()

```

```{r comic characters viz 1}

genderplot1 <- comic_characters %>%
  select("publisher",
         "name",
         "sex",
         "alive",
         "appearances") #%>%
  #mutate(appearances = as.character(appearances),
        #(fct_reorder(sex, "Male Characters",
                      #"Female Characters",
                     #"Genderless Characters",
                     #"Agender Characters",
                    # "NA" = "No Gender")))

ggplot(genderplot1, aes(y = sex)) +
  geom_bar(aes(fill = sex)) +
  scale_colour_viridis_c() +
  labs(title = "Proportion of Characters by Sex", 
       subtitle = "As appear within DC or Marvel Comics",
       x = "Number of Appearances",
       y = "Gender Identification")

```

```{r comic characters viz 2}

genderplot2 <- comic_characters %>%
  select("publisher",
         "name",
         "sex",
         "alive",
         "appearances") %>% 
  drop_na() 

ggplot(genderplot2, aes(y = sex, x = appearances, fill = sex)) +
  geom_jitter() +
  scale_colour_viridis_c() +
  labs(title = "Proportion of Characters by Sex", 
       subtitle = "As appear within DC or Marvel Comics",
       x = "Number of Appearances",
       y = "Gender Identification")
  
```

```{r comic characters viz 3}


```



